### ISSUE TITLE
Upgrade to support Koa v2?

### ISSUE THREAD

**Issue by michaeljoseph** [cyner/swagger-koa#10]
I've recently upgraded an application that uses this project for swagger- would you be amenable to a breaking change PR to support this?

**Comment by janvotava** [comment]
Hello Michael,

I would be totally open to this. We can probably keep current branch as a fork so it will be still compatible with v1, tho I don't have time for this project these days. Feel free to open PR and would be awesome if someone would have time to peer review your diff.

**Comment by michaeljoseph** [comment]
Super! Thanks for the speedy response.
I'll probably have something to share this week...
